development:
  clients:
    default:
      database: dozentron_submission_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: dozentron_submission_development
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: dozentron_submission_production
      hosts:
        - localhost:27017